CREATE ROLE was04 WITH ENCRYPTED PASSWORD 'was0404';
ALTER USER was04 LOGIN;

DROP DATABASE IF EXISTS was04_headoffice;
CREATE DATABASE was04_headoffice WITH ENCODING 'UTF8';
GRANT ALL PRIVILEGES ON DATABASE was04_headoffice TO was04;
ALTER DATABASE was04_headoffice OWNER TO was04;

DROP DATABASE IF EXISTS was04_headoffice_test;
CREATE DATABASE was04_headoffice_test WITH ENCODING 'UTF8';
GRANT ALL PRIVILEGES ON DATABASE was04_headoffice_test TO was04;
ALTER DATABASE was04_headoffice_test OWNER TO was04;




DROP DATABASE IF EXISTS was04_department_wh;
CREATE DATABASE was04_department_wh WITH ENCODING 'UTF8';
GRANT ALL PRIVILEGES ON DATABASE was04_department_wh TO was04;
ALTER DATABASE was04_department_wh OWNER TO was04;

DROP DATABASE IF EXISTS was04_department_wh_test;
CREATE DATABASE was04_department_wh_test WITH ENCODING 'UTF8';
GRANT ALL PRIVILEGES ON DATABASE was04_department_wh_test TO was04;
ALTER DATABASE was04_department_wh_test OWNER TO was04;




DROP DATABASE IF EXISTS was04_department_inv;
CREATE DATABASE was04_department_inv WITH ENCODING 'UTF8';
GRANT ALL PRIVILEGES ON DATABASE was04_department_inv TO was04;
ALTER DATABASE was04_department_inv OWNER TO was04;

DROP DATABASE IF EXISTS was04_department_inv_test;
CREATE DATABASE was04_department_inv_test WITH ENCODING 'UTF8';
GRANT ALL PRIVILEGES ON DATABASE was04_department_inv_test TO was04;
ALTER DATABASE was04_department_inv_test OWNER TO was04;
